package tmux

import (
	"context"
	"strings"
)

// Options of the tmux plugin this project derives from. In plugin mode,
// lyna-tmux reads them from the user's server so an existing configuration
// keeps working unchanged.
const (
	OptClaudeLaunchKey     = "@claude_launch_key"
	OptClaudeListKey       = "@claude_list_key"
	OptClaudeForwardBell   = "@claude_forward_bell"
	OptClaudeSessionPrefix = "@claude_session_prefix"
	OptClaudeCommand       = "@claude_command"
	OptClaudeArgs          = "@claude_args"
	OptClaudePopupWidth    = "@claude_popup_width"
	OptClaudePopupHeight   = "@claude_popup_height"
)

// pluginOptionNames lists the options ReadPluginOptions reads, in field order.
var pluginOptionNames = []string{
	OptClaudeLaunchKey, OptClaudeListKey, OptClaudeForwardBell, OptClaudeSessionPrefix,
	OptClaudeCommand, OptClaudeArgs, OptClaudePopupWidth, OptClaudePopupHeight,
}

// PluginUserOptions are the raw values of the plugin options on a server; an
// unset option is empty.
type PluginUserOptions struct {
	LaunchKey, ListKey, ForwardBell, SessionPrefix string
	Command, Args, PopupWidth, PopupHeight         string
}

// ReadPluginOptions reads every plugin option from the global options of the
// client's server in one invocation.
func (c *Client) ReadPluginOptions(ctx context.Context) (PluginUserOptions, error) {
	fields := make([]string, len(pluginOptionNames))
	for i, name := range pluginOptionNames {
		fields[i] = "#{" + name + "}"
	}
	// One display-message expands every global option, and inserted option
	// values are not expanded again. Separate show-options commands would
	// print nothing for an unset option and misalign the values.
	values, err := c.Display(ctx, "", strings.Join(fields, fieldSep))
	if err != nil {
		return PluginUserOptions{}, err
	}
	f := SplitFields(values)
	if len(f) != len(pluginOptionNames) {
		return PluginUserOptions{}, nil
	}
	return PluginUserOptions{
		LaunchKey: f[0], ListKey: f[1], ForwardBell: f[2], SessionPrefix: f[3],
		Command: f[4], Args: f[5], PopupWidth: f[6], PopupHeight: f[7],
	}, nil
}

// PluginOptions configure plugin mode.
type PluginOptions struct {
	// Bin is the absolute path of the lyna-tmux binary.
	Bin string
	// LaunchKey opens the Claude popup of the current directory and ListKey
	// the agents picker, both in the prefix table; empty leaves the key alone.
	LaunchKey, ListKey string
	// ForwardBell forwards bells from popup sessions to their origin window.
	ForwardBell bool
}

// PluginHook is the alert-bell hook slot plugin mode owns. A fixed array
// index leaves the user's own alert-bell hooks in place and makes applying
// the commands again idempotent.
const PluginHook = "alert-bell[91]"

// PluginSeq returns the commands that install plugin mode on a server the
// user runs: prefix key bindings and the bell forwarding hook.
//
// Bindings hand lyna-tmux only identifiers that are safe in a shell word
// (the pane ID and the client name, a terminal device path); the binary
// reads the directory, window and session of that pane from tmux through the
// TMUX socket run-shell exports, so no path is ever quoted for a shell.
func PluginSeq(o PluginOptions) Seq {
	var s Seq
	if o.LaunchKey != "" {
		s = append(s, Command{
			"bind-key", "-T", "prefix", o.LaunchKey, "run-shell", "-b",
			pluginBinCommand(o.Bin, "popup", "launch") + " --pane #{pane_id} --client #{q:client_name}",
		})
	}
	if o.ListKey != "" {
		s = append(s, Command{
			"bind-key", "-T", "prefix", o.ListKey, "run-shell", "-b",
			pluginBinCommand(o.Bin, "popup", "agents") + " --pane #{pane_id} --client #{q:client_name}",
		})
	}
	if o.ForwardBell {
		// Session IDs are '$' and digits, which #{q:} escapes completely.
		hook := Cmd("run-shell", "-b", pluginBinCommand(o.Bin, "bell-forward")+" #{q:hook_session}")
		s = append(s, Command{"set-hook", "-g", PluginHook, hook.String()})
	} else {
		s = append(s, Command{"set-hook", "-gu", PluginHook})
	}
	return s
}

// pluginBinCommand renders the start of a run-shell command line, which tmux
// format-expands before the shell parses it.
func pluginBinCommand(bin string, args ...string) string {
	return FormatEscape(ShellJoin(append([]string{bin}, args...)...))
}

// PluginConf renders PluginSeq as a configuration file the user can source
// from their own tmux configuration.
func PluginConf(o PluginOptions) string {
	w := &confWriter{}
	w.comment("lyna-tmux plugin mode. Generated by `lyna-tmux plugin tmux --write`; do not edit.")
	w.comment("Source it from your tmux configuration: source-file <this file>")
	for _, c := range PluginSeq(o) {
		w.seq(Seq{c})
	}
	return w.b.String()
}
