package claudecfg

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

// Teammate modes: where Claude Code opens the teammates of a team.
const (
	// TeammateLmux opens every teammate in a pane of the workspace, through
	// the launcher this package renders. Claude Code is told "tmux", which is
	// the backend that splits the window the lead runs in.
	TeammateLmux = "lmux"
	// TeammateAuto leaves the choice to Claude Code.
	TeammateAuto = "auto"
	// TeammateInProcess keeps every teammate inside the lead's own session.
	TeammateInProcess = "in-process"
	// TeammateITerm2 opens teammates as terminal splits.
	TeammateITerm2 = "iterm2"
)

// TeammateModes lists the accepted claude.teammate_mode values.
func TeammateModes() []string {
	return []string{TeammateLmux, TeammateAuto, TeammateInProcess, TeammateITerm2}
}

// ErrTeammateMode reports a teammate mode that is not one of TeammateModes.
var ErrTeammateMode = errors.New("claudecfg: unknown teammate mode")

// TeammateInWorkspace reports whether mode opens every teammate in a pane of
// the workspace, through our launcher. An unset mode is that one: it is the
// default, and it is the only mode that needs a launcher written.
func TeammateInWorkspace(mode string) bool { return mode == "" || mode == TeammateLmux }

// SettingsTeammateMode maps a teammate mode to the value written to the
// settings file. Claude Code accepts four backends and lmux is not one of
// them: it is the tmux backend, with the pane taken over by our launcher.
func SettingsTeammateMode(mode string) (string, error) {
	if TeammateInWorkspace(mode) {
		return "tmux", nil
	}
	switch mode {
	case TeammateAuto, TeammateInProcess, TeammateITerm2:
		return mode, nil
	}
	return "", fmt.Errorf("%w %q (one of: %s)", ErrTeammateMode, mode, strings.Join(TeammateModes(), ", "))
}

// ErrLauncherPath reports a path the launcher cannot be built from.
var ErrLauncherPath = errors.New("claudecfg: launcher path must be absolute and free of newlines")

// TeammateLauncher renders the script Claude Code runs in place of the agent
// when a teammate opens.
//
// Claude Code reads CLAUDE_CODE_TEAMMATE_COMMAND as one executable, not as a
// command line: whatever the variable holds is quoted as a single word and the
// teammate's own arguments are appended to it. A script is therefore the only
// way to reach a subcommand of ours, and it is what carries the guarantee that
// a team never fails to start: when our binary is gone or is not executable,
// the script runs the agent exactly as Claude Code would have.
//
// Both paths are quoted as one shell word each, so a directory holding a
// space, a quote or a dollar sign is run as written.
func TeammateLauncher(lmuxPath, claudePath string) (string, error) {
	for _, p := range []string{lmuxPath, claudePath} {
		if !filepath.IsAbs(p) || strings.ContainsAny(p, "\n\x00") {
			return "", fmt.Errorf("%w (got %q)", ErrLauncherPath, p)
		}
	}
	lmux, claude := shellQuote(lmuxPath), shellQuote(claudePath)
	return "#!/bin/sh\n" +
		"# Generated by lyna-tmux. Claude Code runs this in the pane it opened for a\n" +
		"# teammate, with the teammate's own arguments appended. It hands the pane to\n" +
		"# lmux, which labels it and puts the layout back before running the agent.\n" +
		"# If lmux cannot run, the agent starts anyway and the team is unaffected.\n" +
		"if [ -x " + lmux + " ]; then\n" +
		"\texec " + lmux + " teammate --claude " + claude + " -- \"$@\"\n" +
		"fi\n" +
		"exec " + claude + " \"$@\"\n", nil
}

// LauncherFileName is the content-addressed name of a rendered launcher, so
// two workspaces resolving the same pair of binaries share one file and a
// changed binary writes a new one.
func LauncherFileName(script string) string {
	sum := sha256.Sum256([]byte(script))
	return hex.EncodeToString(sum[:8]) + ".sh"
}

var launcherFileNamePattern = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile(`^[0-9a-f]{16}\.sh$`) })

// IsLauncherFileName reports whether name has the LauncherFileName shape.
func IsLauncherFileName(name string) bool { return launcherFileNamePattern().MatchString(name) }
