// Package claudetheme turns the workspace palettes into Claude Code custom
// themes, so the agent's own interface matches the tmux status line, borders
// and pickers around it.
//
// Claude Code loads custom themes from JSON files in <config dir>/themes and
// from the themes/ directory of installed plugins. A file holds an optional
// display name, a built-in base preset and a sparse map of color token
// overrides; unknown top-level fields, unknown tokens and invalid color values
// are ignored by Claude Code, and its /theme editor saves only name, base and
// overrides back.
//
// Generated files carry two extra top-level fields, generator and checksum,
// which identify an untouched lyna-tmux file. Write replaces a theme file only
// when both still match, so a theme the user wrote, or edited by hand or in the
// /theme editor, is never overwritten.
package claudetheme

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"sync"

	"github.com/bayoudhdev/lyna-claude-tmux/internal/domain/theme"
	"github.com/bayoudhdev/lyna-claude-tmux/internal/fsx"
)

const (
	// Generator is the value of the generator field in every generated file.
	Generator = "lyna-tmux"
	// DirName is the theme directory inside Claude Code's config directory and
	// inside a plugin.
	DirName = "themes"
	// MaxFileBytes is the size above which Claude Code skips a theme file.
	MaxFileBytes = 256 << 10
	// filePrefix starts every generated file name.
	filePrefix = "lyna-"
	// checksumPrefix names the digest algorithm inside the checksum field.
	checksumPrefix = "sha256:"
)

var (
	// ErrNotGenerated reports an existing theme file that lyna-tmux did not
	// write or that was changed since; Write leaves it alone.
	ErrNotGenerated = errors.New("claudetheme: existing theme file was not generated by lyna-tmux or was edited")
	// ErrPaletteName reports a palette name that cannot form a theme file name.
	ErrPaletteName = errors.New("claudetheme: palette name must be lowercase letters, digits and hyphens")
)

// presets are the base themes Claude Code accepts; any other base reads as
// dark.
var presets = []string{"dark", "light", "dark-daltonized", "light-daltonized", "dark-ansi", "light-ansi"}

// tokens are the color tokens every Claude Code base theme defines (2.1.273).
// Overrides for any other name are dropped when the file is loaded.
var tokens = []string{
	"autoAccept", "autoAcceptShimmer", "background", "bashBorder", "bashMessageBackgroundColor",
	"blue_FOR_SUBAGENTS_ONLY", "briefLabelClaude", "briefLabelYou", "chromeYellow", "claude",
	"claudeBlueShimmer_FOR_SYSTEM_SPINNER", "claudeBlue_FOR_SYSTEM_SPINNER", "claudeShimmer",
	"clawd_background", "clawd_body", "composerSidebarBackground", "cyan_FOR_SUBAGENTS_ONLY",
	"diffAdded", "diffAddedDimmed", "diffAddedWord", "diffRemoved", "diffRemovedDimmed",
	"diffRemovedWord", "effortUltra", "error", "fastMode", "fastModeShimmer",
	"green_FOR_SUBAGENTS_ONLY", "ide", "inactive", "inactiveShimmer", "inverseText",
	"memoryBackgroundColor", "merged", "orange_FOR_SUBAGENTS_ONLY", "permission", "permissionShimmer",
	"pink_FOR_SUBAGENTS_ONLY", "planMode", "professionalBlue", "promptBorder", "promptBorderShimmer",
	"purple_FOR_SUBAGENTS_ONLY", "rainbow_blue", "rainbow_blue_shimmer", "rainbow_green",
	"rainbow_green_shimmer", "rainbow_indigo", "rainbow_indigo_shimmer", "rainbow_orange",
	"rainbow_orange_shimmer", "rainbow_red", "rainbow_red_shimmer", "rainbow_violet",
	"rainbow_violet_shimmer", "rainbow_yellow", "rainbow_yellow_shimmer", "rate_limit_empty",
	"rate_limit_fill", "red_FOR_SUBAGENTS_ONLY", "remember", "selectionBg", "skill", "subtle",
	"success", "suggestion", "text", "userMessageBackground", "userMessageBackgroundHover", "warning",
	"warningShimmer", "yellow_FOR_SUBAGENTS_ONLY",
}

// Presets returns the base theme names Claude Code accepts.
func Presets() []string { return slices.Clone(presets) }

// Tokens returns the color token names Claude Code accepts in overrides,
// sorted.
func Tokens() []string { return slices.Clone(tokens) }

// ansiNames are Claude Code's names for the 16 terminal palette colors.
var ansiNames = [16]string{
	"black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
	"blackBright", "redBright", "greenBright", "yellowBright", "blueBright", "magentaBright", "cyanBright", "whiteBright",
}

// colorValue matches the color value syntaxes Claude Code accepts, exactly as
// it does. It is compiled on first use: the package is linked into the hook
// and statusline commands, which Claude Code starts on every tool call, and a
// compiled pattern at package init would cost every one of them.
var colorValue = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile(`^rgb\(\s?\d{1,3},\s?\d{1,3},\s?\d{1,3}\s?\)$|^#[0-9a-fA-F]{6}$|^#[0-9a-fA-F]{3}$|^ansi256\(\d{1,3}\)$`)
})

// ValidColor reports whether Claude Code accepts s as a color value:
// rgb(r,g,b), #rrggbb, #rgb, ansi256(n) or ansi:<name>.
func ValidColor(s string) bool {
	if name, ok := strings.CutPrefix(s, "ansi:"); ok {
		return slices.Contains(ansiNames[:], name)
	}
	return colorValue().MatchString(s)
}

// File is the JSON document of one theme file.
type File struct {
	Name      string            `json:"name"`
	Base      string            `json:"base"`
	Overrides map[string]string `json:"overrides"`
	Generator string            `json:"generator,omitempty"`
	Checksum  string            `json:"checksum,omitempty"`
}

// checksum digests the fields Claude Code reads. encoding/json writes map
// keys sorted, so equal content always yields the same digest.
func (f File) checksum() string {
	data, _ := json.Marshal(struct {
		Name      string            `json:"name"`
		Base      string            `json:"base"`
		Overrides map[string]string `json:"overrides"`
	}{f.Name, f.Base, f.Overrides})
	sum := sha256.Sum256(data)
	return checksumPrefix + hex.EncodeToString(sum[:])
}

// FileName returns the theme file name for a palette, "lyna-<name>.json".
// Claude Code uses the name without .json as the theme's slug.
func FileName(paletteName string) string { return filePrefix + paletteName + ".json" }

// DisplayName returns the label /theme shows for a palette's theme: "Lyna"
// for the default palette and "Lyna <Name>" for the others.
func DisplayName(paletteName string) string {
	switch paletteName {
	case "", "lyna":
		return "Lyna"
	case "ansi":
		return "Lyna ANSI"
	}
	return "Lyna " + strings.ToUpper(paletteName[:1]) + paletteName[1:]
}

func validPaletteName(name string) bool {
	if name == "" || name[0] == '-' || name[len(name)-1] == '-' {
		return false
	}
	for i := range len(name) {
		c := name[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '-' {
			return false
		}
	}
	return true
}

// Generate returns the theme file for a palette. The palette's semantic
// colors replace the tokens they correspond to; everything else falls through
// to the matching base preset.
func Generate(p theme.Palette) ([]byte, error) {
	if !validPaletteName(p.Name) {
		return nil, fmt.Errorf("%w: %q", ErrPaletteName, p.Name)
	}
	f := File{Name: DisplayName(p.Name), Base: base(p), Overrides: overrides(p), Generator: Generator}
	f.Checksum = f.checksum()
	return encode(f)
}

func encode(f File) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// base picks the preset whose untouched tokens suit the palette: the ANSI
// presets for a palette built from terminal colors, so the whole interface
// follows the terminal's scheme, and dark or light otherwise.
func base(p theme.Palette) string {
	b := "dark"
	if !p.Dark {
		b = "light"
	}
	if p.Bg.Indexed {
		b += "-ansi"
	}
	return b
}

// overrides maps the palette onto Claude Code tokens.
func overrides(p theme.Palette) map[string]string {
	return map[string]string{
		// Brand and text.
		"claude":            value(p.Accent),
		"claudeShimmer":     value(shimmer(p.Accent)),
		"text":              value(p.Text),
		"inverseText":       value(p.Bg),
		"inactive":          value(p.Muted),
		"inactiveShimmer":   value(shimmer(p.Muted)),
		"subtle":            value(p.Border),
		"suggestion":        value(p.Accent2),
		"permission":        value(p.Accent2),
		"permissionShimmer": value(shimmer(p.Accent2)),
		"remember":          value(p.Accent2),
		"briefLabelYou":     value(p.Accent2),
		"briefLabelClaude":  value(p.Accent),

		// Status.
		"success":        value(p.Success),
		"error":          value(p.Danger),
		"warning":        value(p.Warning),
		"warningShimmer": value(shimmer(p.Warning)),

		// Input box and modes.
		"promptBorder":        value(p.Muted),
		"promptBorderShimmer": value(shimmer(p.Muted)),
		"planMode":            value(p.Accent2),
		"autoAccept":          value(p.Busy),
		"autoAcceptShimmer":   value(shimmer(p.Busy)),
		"bashBorder":          value(p.Warning),
		"ide":                 value(p.Accent2),

		// Diffs: tinted backgrounds from the status colors.
		"diffAdded":         value(tint(p, p.Success, 0.30)),
		"diffRemoved":       value(tint(p, p.Danger, 0.30)),
		"diffAddedDimmed":   value(tint(p, p.Success, 0.15)),
		"diffRemovedDimmed": value(tint(p, p.Danger, 0.15)),
		"diffAddedWord":     value(tint(p, p.Success, 0.60)),
		"diffRemovedWord":   value(tint(p, p.Danger, 0.60)),

		// Transcript surfaces.
		"userMessageBackground":      value(p.Surface),
		"userMessageBackgroundHover": value(p.Overlay),
		"bashMessageBackgroundColor": value(p.Surface),
		"memoryBackgroundColor":      value(p.Surface),
		"selectionBg":                value(p.Overlay),

		// Usage meter.
		"rate_limit_fill":  value(p.Accent),
		"rate_limit_empty": value(p.Border),
	}
}

// value spells a color the way Claude Code reads it.
func value(c theme.Color) string {
	if c.Indexed {
		return "ansi:" + ansiNames[c.ANSI&15]
	}
	return c.Hex()
}

// shimmer is the lighter partner of a color that animated gradients sweep
// to. A terminal palette color uses its bright variant.
func shimmer(c theme.Color) theme.Color {
	if c.Indexed {
		if c.ANSI < 8 {
			return theme.ANSI(c.ANSI + 8)
		}
		return c
	}
	return mix(c, theme.RGB(255, 255, 255), 0.25)
}

// tint blends a status color into the palette background, the way diff
// backgrounds stay readable under text. Terminal palettes cannot blend, so
// they use the color for strong tints and its normal variant otherwise.
func tint(p theme.Palette, c theme.Color, amount float64) theme.Color {
	if c.Indexed || p.Bg.Indexed {
		if !c.Indexed {
			return c
		}
		if amount >= 0.5 {
			return shimmer(c)
		}
		return theme.ANSI(c.ANSI % 8)
	}
	return mix(p.Bg, c, amount)
}

// mix moves a toward b by amount (0 to 1).
func mix(a, b theme.Color, amount float64) theme.Color {
	ch := func(x, y uint8) uint8 {
		return uint8(math.Round(float64(x) + (float64(y)-float64(x))*amount))
	}
	return theme.RGB(ch(a.R, b.R), ch(a.G, b.G), ch(a.B, b.B))
}

// Outcome is what Write did with one theme file.
type Outcome string

// Write outcomes.
const (
	Created   Outcome = "created"
	Updated   Outcome = "updated"
	Unchanged Outcome = "unchanged"
	Refused   Outcome = "refused"
	Failed    Outcome = "failed"
)

// Result describes one file handled by Write.
type Result struct {
	Palette string
	Path    string
	Outcome Outcome
	// Err is set for Refused (wrapping ErrNotGenerated) and Failed.
	Err error
}

// Report is the outcome of Write.
type Report struct {
	// Dir is the themes directory.
	Dir string
	// CreatedDir reports that Write created Dir. Claude Code sessions started
	// before it existed only see the themes after a restart.
	CreatedDir bool
	Files      []Result
}

// Write generates the theme of each palette into <claudeHome>/themes. A file
// is created when missing, replaced only when it is an untouched earlier
// lyna-tmux file, and otherwise refused. Files are written atomically with
// mode 0600 and never through a symbolic link. The returned error joins every
// per-file error; the report lists each file either way.
func Write(claudeHome string, palettes ...theme.Palette) (Report, error) {
	var rep Report
	if !filepath.IsAbs(claudeHome) {
		return rep, fmt.Errorf("claudetheme: config directory must be absolute: %q", claudeHome)
	}
	info, err := os.Stat(claudeHome)
	if err != nil {
		return rep, fmt.Errorf("claudetheme: config directory: %w", err)
	}
	if !info.IsDir() {
		return rep, fmt.Errorf("claudetheme: config directory %s: %w", claudeHome, fsx.ErrNotDir)
	}
	rep.Dir = filepath.Join(claudeHome, DirName)
	rep.CreatedDir, err = ensureDir(rep.Dir)
	if err != nil {
		return rep, err
	}

	var errs []error
	for _, p := range palettes {
		res := writeOne(rep.Dir, p)
		if res.Err != nil {
			errs = append(errs, res.Err)
		}
		rep.Files = append(rep.Files, res)
	}
	return rep, errors.Join(errs...)
}

// ensureDir creates the themes directory when missing. An existing one must be
// a real directory, not a link.
func ensureDir(dir string) (bool, error) {
	err := os.Mkdir(dir, fsx.PrivateDir)
	if err == nil {
		return true, nil
	}
	if !errors.Is(err, fs.ErrExist) {
		return false, fmt.Errorf("claudetheme: create %s: %w", dir, err)
	}
	info, err := os.Lstat(dir)
	if err != nil {
		return false, fmt.Errorf("claudetheme: %w", err)
	}
	if info.Mode()&fs.ModeSymlink != 0 {
		return false, fmt.Errorf("claudetheme: %s: %w", dir, fsx.ErrSymlink)
	}
	if !info.IsDir() {
		return false, fmt.Errorf("claudetheme: %s: %w", dir, fsx.ErrNotDir)
	}
	return false, nil
}

func writeOne(dir string, p theme.Palette) Result {
	res := Result{Palette: p.Name}
	data, err := Generate(p)
	if err != nil {
		res.Outcome, res.Err = Failed, err
		return res
	}
	res.Path = filepath.Join(dir, FileName(p.Name))

	existing, err := fsx.ReadFileNoFollow(res.Path, MaxFileBytes)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		res.Outcome = Created
	case err != nil:
		// A link, a non-regular file or an oversized file is not ours.
		res.Outcome, res.Err = Refused, fmt.Errorf("%s: %w (%w)", res.Path, ErrNotGenerated, err)
		return res
	case bytes.Equal(existing, data):
		res.Outcome = Unchanged
		return res
	case !Recognize(existing):
		res.Outcome, res.Err = Refused, fmt.Errorf("%s: %w", res.Path, ErrNotGenerated)
		return res
	default:
		res.Outcome = Updated
	}
	if err := fsx.WriteFileAtomic(res.Path, data, fsx.PrivateFile); err != nil {
		res.Outcome, res.Err = Failed, fmt.Errorf("claudetheme: %w", err)
	}
	return res
}

// Recognize reports whether data is a theme file written by lyna-tmux and not
// changed since: it names the generator and its checksum still matches the
// name, base and overrides it holds.
func Recognize(data []byte) bool {
	var f File
	if json.Unmarshal(data, &f) != nil || f.Generator != Generator {
		return false
	}
	return f.Checksum == f.checksum()
}
