-- Generated by lyna-tmux for "lyna-tmux review". It is rewritten before a
-- review starts, so local edits do not last.

local plugin = "/home/dev/.local/share/lyna-tmux/review/codediff.nvim"
local system = {}
for _, kind in ipairs({ "config_dirs", "data_dirs" }) do
  for _, dir in ipairs(vim.fn.stdpath(kind)) do
    for _, suffix in ipairs({ "", "/after", "/site", "/site/after" }) do
      system[dir .. suffix] = true
    end
  end
end
local function without_system(entries)
  local kept = {}
  for _, entry in ipairs(entries) do
    if not system[entry] then
      kept[#kept + 1] = entry
    end
  end
  return kept
end
vim.opt.runtimepath = without_system(vim.opt.runtimepath:get())
vim.opt.packpath = without_system(vim.opt.packpath:get())
vim.opt.runtimepath:prepend(plugin)

vim.o.modeline = false
vim.o.exrc = false
vim.o.swapfile = false
vim.o.shadafile = "NONE"
vim.o.termguicolors = false
vim.o.background = "dark"

local ok, err = pcall(function()
  require("codediff").setup({
    diff = {
      filler_text = "/",
    },
    explorer = {
      auto_refresh = true,
      indent_markers = false,
      ellipsis = "...",
      icons = {
        folder_closed = "+",
        folder_open = "-",
      },
    },
  })
end)
if not ok then
  vim.g.lyna_tmux_review_setup_error = tostring(err)
end

-- Neovim names a window and a tab after the buffer in it, and a diff buffer is
-- a codediff:///<repository>///<revision>/<file> URL: shortened to the width
-- there is, it becomes one character per path component and names neither the
-- file nor the revision it holds. Both lines are built from the URL instead.
-- A status line takes the text as it is, a tab line reads it as a format, so
-- only the tab line escapes it.
local function revision(rev)
  if rev:sub(1, 1) == ":" then
    return "index"
  end
  if #rev > 8 and rev:match("^%x+$") then
    return rev:sub(1, 8)
  end
  return rev
end

function _G.lyna_tmux_review_label(name)
  if not name or name == "" then
    return "[no name]"
  end
  local rev, file = name:match("^codediff:///.-///([^/]+)/(.+)$")
  if file then
    return file .. "  @ " .. revision(rev)
  end
  local panel = name:match("^CodeDiff (%a+) %[%d+%]$")
  if panel then
    return panel
  end
  return vim.fn.fnamemodify(name, ":~:.")
end

function _G.lyna_tmux_review_tabline()
  local current = vim.api.nvim_get_current_tabpage()
  local out = {}
  for i, tab in ipairs(vim.api.nvim_list_tabpages()) do
    local label = "[no name]"
    local ok, win = pcall(vim.api.nvim_tabpage_get_win, tab)
    if ok then
      -- bufname() is the name as the plugin set it; nvim_buf_get_name() would
      -- turn the name of a panel into a path under the working directory.
      label = _G.lyna_tmux_review_label(vim.fn.bufname(vim.api.nvim_win_get_buf(win)))
    end
    out[#out + 1] = (tab == current and "%#TabLineSel#" or "%#TabLine#")
      .. "%" .. i .. "T " .. (label:gsub("%%", "%%%%")) .. " "
  end
  return table.concat(out) .. "%#TabLineFill#%T"
end

vim.o.tabline = "%!v:lua.lyna_tmux_review_tabline()"
-- %m would mark every diff buffer with the [-] of a read-only one, which all of
-- them are; only unsaved work in the file under review is worth a marker. The
-- space before it is its own item because Neovim drops the leading space of an
-- expression that follows another one.
vim.o.statusline = " %{v:lua.lyna_tmux_review_label(bufname())} %{&modified ? '[+]' : ''}%=%l:%c  %P "

-- codediff.nvim opens its review in a new tab, which leaves the empty buffer
-- Neovim starts with in a tab of its own. Closing it gives the review the whole
-- window, and a lone tab draws no tab line at all.
vim.api.nvim_create_autocmd("TabNewEntered", {
  once = true,
  callback = function()
    vim.schedule(function()
      local tabs = vim.api.nvim_list_tabpages()
      if #tabs < 2 or tabs[1] == vim.api.nvim_get_current_tabpage() then
        return
      end
      local wins = vim.api.nvim_tabpage_list_wins(tabs[1])
      if #wins ~= 1 then
        return
      end
      local buf = vim.api.nvim_win_get_buf(wins[1])
      local lines = vim.api.nvim_buf_get_lines(buf, 0, 2, false)
      if vim.api.nvim_buf_get_name(buf) ~= "" or vim.bo[buf].modified then
        return
      end
      if #lines > 1 or (lines[1] or "") ~= "" then
        return
      end
      pcall(vim.api.nvim_command, "tabclose 1")
    end)
  end,
})
