-- Generated by lyna-tmux for "lmux review". It is rewritten before a
-- review starts, so local edits do not last.

local plugin = "/home/dev/.local/share/lyna-tmux/review/codediff.nvim"
local system = {}
for _, kind in ipairs({ "config_dirs", "data_dirs" }) do
  for _, dir in ipairs(vim.fn.stdpath(kind)) do
    for _, suffix in ipairs({ "", "/after", "/site", "/site/after" }) do
      system[dir .. suffix] = true
    end
  end
end
local function without_system(entries)
  local kept = {}
  for _, entry in ipairs(entries) do
    if not system[entry] then
      kept[#kept + 1] = entry
    end
  end
  return kept
end
vim.opt.runtimepath = without_system(vim.opt.runtimepath:get())
vim.opt.packpath = without_system(vim.opt.packpath:get())
vim.opt.runtimepath:prepend(plugin)

vim.o.modeline = false
vim.o.exrc = false
vim.o.swapfile = false
vim.o.shadafile = "NONE"
vim.o.termguicolors = true
vim.o.background = "dark"

-- The workspace palette, on the groups the syntax rules use and on the
-- captures nvim-treesitter sets, so a parsed buffer and an unparsed one
-- are colored alike.
for _, group in ipairs({
  { "Normal", { fg = "#e6edf3", bg = "#0d1117" } },
  { "NormalNC", { fg = "#e6edf3", bg = "#0d1117" } },
  { "NormalFloat", { fg = "#e6edf3", bg = "#161b22" } },
  { "FloatBorder", { fg = "#39d353", bg = "#161b22" } },
  { "WinSeparator", { fg = "#30363d", bg = "#0d1117" } },
  { "CursorLine", { bg = "#10151b" } },
  { "CursorLineNr", { fg = "#39d353", bold = true } },
  { "LineNr", { fg = "#30363d" } },
  { "SignColumn", { bg = "#0d1117" } },
  { "Visual", { bg = "#30527a" } },
  { "Search", { fg = "#0d1117", bg = "#f0b72f" } },
  { "IncSearch", { fg = "#0d1117", bg = "#f0b72f" } },
  { "MatchParen", { fg = "#f0b72f", bold = true } },
  { "Cursor", { reverse = true } },
  { "Pmenu", { fg = "#e6edf3", bg = "#161b22" } },
  { "PmenuSel", { fg = "#0d1117", bg = "#39d353" } },
  { "StatusLine", { fg = "#e6edf3", bg = "#161b22" } },
  { "StatusLineNC", { fg = "#7d8590", bg = "#262d38" } },
  { "TabLine", { fg = "#7d8590", bg = "#262d38" } },
  { "TabLineSel", { fg = "#0d1117", bg = "#39d353", bold = true } },
  { "TabLineFill", { bg = "#0d1117" } },
  { "Title", { fg = "#39d353", bold = true } },
  { "Directory", { fg = "#58a6ff" } },
  { "ErrorMsg", { fg = "#ff5f56", bold = true } },
  { "WarningMsg", { fg = "#f0b72f" } },
  { "NonText", { fg = "#30363d" } },
  { "Whitespace", { fg = "#30363d" } },
  { "Folded", { fg = "#7d8590", bg = "#161b22" } },
  { "DiffAdd", { bg = "#163b24" } },
  { "DiffDelete", { fg = "#ff5f56", bg = "#422224" } },
  { "DiffChange", { bg = "#1d314a" } },
  { "DiffText", { bg = "#2e547f" } },
  { "@attribute", { fg = "#f0b72f", italic = true } },
  { "@boolean", { fg = "#ab83ab" } },
  { "@character", { fg = "#f0b72f" } },
  { "@comment", { fg = "#676e78", italic = true } },
  { "@comment.todo", { fg = "#f0b72f", bold = true } },
  { "@conditional", { fg = "#ff5f56" } },
  { "@constant", { fg = "#ab83ab" } },
  { "@constant.builtin", { fg = "#ab83ab" } },
  { "@constructor", { fg = "#39d353" } },
  { "@error", { fg = "#ff5f56", bold = true } },
  { "@exception", { fg = "#ff5f56" } },
  { "@field", { fg = "#f0b72f", italic = true } },
  { "@float", { fg = "#ab83ab" } },
  { "@function", { fg = "#39d353" } },
  { "@function.call", { fg = "#39d353" } },
  { "@function.method", { fg = "#39d353" } },
  { "@include", { fg = "#ab83ab" } },
  { "@keyword", { fg = "#ff5f56" } },
  { "@keyword.function", { fg = "#ff5f56" } },
  { "@keyword.operator", { fg = "#ff5f56" } },
  { "@keyword.return", { fg = "#ff5f56" } },
  { "@method", { fg = "#39d353" } },
  { "@module", { fg = "#58a6ff", italic = true } },
  { "@namespace", { fg = "#58a6ff", italic = true } },
  { "@none", { fg = "#e6edf3" } },
  { "@number", { fg = "#ab83ab" } },
  { "@operator", { fg = "#ff5f56" } },
  { "@parameter", { fg = "#f0b72f", italic = true } },
  { "@preproc", { fg = "#ab83ab" } },
  { "@property", { fg = "#f0b72f", italic = true } },
  { "@punctuation.bracket", { fg = "#7d8590" } },
  { "@punctuation.delimiter", { fg = "#7d8590" } },
  { "@punctuation.special", { fg = "#7d8590" } },
  { "@repeat", { fg = "#ff5f56" } },
  { "@string", { fg = "#f0b72f" } },
  { "@string.escape", { fg = "#f0b72f" } },
  { "@tag.attribute", { fg = "#f0b72f", italic = true } },
  { "@text", { fg = "#e6edf3" } },
  { "@text.danger", { fg = "#ff5f56", bold = true } },
  { "@text.todo", { fg = "#f0b72f", bold = true } },
  { "@type", { fg = "#58a6ff", italic = true } },
  { "@type.builtin", { fg = "#58a6ff", italic = true } },
  { "@type.definition", { fg = "#58a6ff", italic = true } },
  { "@variable", { fg = "#e6edf3" } },
  { "@variable.builtin", { fg = "#e6edf3" } },
  { "@variable.parameter", { fg = "#f0b72f", italic = true } },
  { "Boolean", { fg = "#ab83ab" } },
  { "Character", { fg = "#f0b72f" } },
  { "Comment", { fg = "#676e78", italic = true } },
  { "Conditional", { fg = "#ff5f56" } },
  { "Constant", { fg = "#ab83ab" } },
  { "Define", { fg = "#ab83ab" } },
  { "Delimiter", { fg = "#7d8590" } },
  { "Error", { fg = "#ff5f56", bold = true } },
  { "Exception", { fg = "#ff5f56" } },
  { "Float", { fg = "#ab83ab" } },
  { "Function", { fg = "#39d353" } },
  { "Identifier", { fg = "#39d353" } },
  { "Include", { fg = "#ab83ab" } },
  { "Keyword", { fg = "#ff5f56" } },
  { "Macro", { fg = "#ab83ab" } },
  { "Number", { fg = "#ab83ab" } },
  { "Operator", { fg = "#ff5f56" } },
  { "PreProc", { fg = "#ab83ab" } },
  { "Repeat", { fg = "#ff5f56" } },
  { "Statement", { fg = "#ff5f56" } },
  { "StorageClass", { fg = "#58a6ff", italic = true } },
  { "String", { fg = "#f0b72f" } },
  { "Structure", { fg = "#58a6ff", italic = true } },
  { "Todo", { fg = "#f0b72f", bold = true } },
  { "Type", { fg = "#58a6ff", italic = true } },
}) do
  pcall(vim.api.nvim_set_hl, 0, group[1], group[2])
end
vim.api.nvim_create_autocmd("FileType", {
  callback = function(args)
    pcall(vim.treesitter.start, args.buf)
  end,
})

local ok, err = pcall(function()
  require("codediff").setup({
    highlights = {
      line_insert = "#163b24",
      line_delete = "#422224",
      char_insert = "#206832",
      char_delete = "#793433",
      conflict_sign = "#f0b72f",
      conflict_sign_resolved = "#7d8590",
      conflict_sign_accepted = "#39d353",
      conflict_sign_rejected = "#ff5f56",
    },
    diff = {
      filler_text = "╱",
    },
    explorer = {
      auto_refresh = true,
      indent_markers = true,
      ellipsis = "…",
      icons = {
        folder_closed = "▸",
        folder_open = "▾",
      },
    },
  })
end)
if not ok then
  vim.g.lyna_tmux_review_setup_error = tostring(err)
end

-- Neovim names a window and a tab after the buffer in it, and a diff buffer is
-- a codediff:///<repository>///<revision>/<file> URL: shortened to the width
-- there is, it becomes one character per path component and names neither the
-- file nor the revision it holds. Both lines are built from the URL instead.
-- A status line takes the text as it is, a tab line reads it as a format, so
-- only the tab line escapes it.
local function revision(rev)
  if rev:sub(1, 1) == ":" then
    return "index"
  end
  if #rev > 8 and rev:match("^%x+$") then
    return rev:sub(1, 8)
  end
  return rev
end

-- A review splits the window three ways, so a label often has fewer columns
-- than it needs. Neovim would cut it at the front, which turns README.md into
-- <ADME.md: the shorter forms below are tried in order instead. The room is
-- what the window being drawn has left once the marker and the ruler on the
-- other side of the line have taken theirs.
local ruler = 16

local function fit(forms, measure)
  if not measure then
    return forms[1]
  end
  -- Neovim draws a status line with its own window current, so this is the
  -- width of that window and not of the one the cursor is in.
  local width = vim.fn.winwidth(0)
  if width <= 0 then
    return forms[1]
  end
  local room = width - ruler
  for _, form in ipairs(forms) do
    if vim.fn.strdisplaywidth(form) <= room then
      return form
    end
  end
  return forms[#forms]
end

-- measure is set by the status line, which is drawn in one window and has its
-- width to respect. The tab line spans the whole editor and passes nothing.
function _G.lyna_tmux_review_label(name, measure)
  if not name or name == "" then
    return "[no name]"
  end
  local rev, file = name:match("^codediff:///.-///([^/]+)/(.+)$")
  if file then
    return fit({ file .. "  @ " .. revision(rev), file, vim.fn.fnamemodify(file, ":t") }, measure)
  end
  local panel = name:match("^CodeDiff (%a+) %[%d+%]$")
  if panel then
    return panel
  end
  local short = vim.fn.fnamemodify(name, ":~:.")
  return fit({ short, vim.fn.fnamemodify(short, ":t") }, measure)
end

function _G.lyna_tmux_review_tabline()
  local current = vim.api.nvim_get_current_tabpage()
  local out = {}
  for i, tab in ipairs(vim.api.nvim_list_tabpages()) do
    local label = "[no name]"
    local ok, win = pcall(vim.api.nvim_tabpage_get_win, tab)
    if ok then
      -- bufname() is the name as the plugin set it; nvim_buf_get_name() would
      -- turn the name of a panel into a path under the working directory.
      label = _G.lyna_tmux_review_label(vim.fn.bufname(vim.api.nvim_win_get_buf(win)))
    end
    out[#out + 1] = (tab == current and "%#TabLineSel#" or "%#TabLine#")
      .. "%" .. i .. "T " .. (label:gsub("%%", "%%%%")) .. " "
  end
  return table.concat(out) .. "%#TabLineFill#%T"
end

vim.o.tabline = "%!v:lua.lyna_tmux_review_tabline()"
-- %m would mark every diff buffer with the [-] of a read-only one, which all of
-- them are; only unsaved work in the file under review is worth a marker. The
-- space before it is its own item because Neovim drops the leading space of an
-- expression that follows another one.
vim.o.statusline = " %{v:lua.lyna_tmux_review_label(bufname(), 1)} %{&modified ? '[+]' : ''}%=%l:%c  %P "

-- codediff.nvim opens its review in a new tab, which leaves the empty buffer
-- Neovim starts with in a tab of its own. Closing it gives the review the whole
-- window, and a lone tab draws no tab line at all.
vim.api.nvim_create_autocmd("TabNewEntered", {
  once = true,
  callback = function()
    vim.schedule(function()
      local tabs = vim.api.nvim_list_tabpages()
      if #tabs < 2 or tabs[1] == vim.api.nvim_get_current_tabpage() then
        return
      end
      local wins = vim.api.nvim_tabpage_list_wins(tabs[1])
      if #wins ~= 1 then
        return
      end
      local buf = vim.api.nvim_win_get_buf(wins[1])
      local lines = vim.api.nvim_buf_get_lines(buf, 0, 2, false)
      if vim.api.nvim_buf_get_name(buf) ~= "" or vim.bo[buf].modified then
        return
      end
      if #lines > 1 or (lines[1] or "") ~= "" then
        return
      end
      pcall(vim.api.nvim_command, "tabclose 1")
    end)
  end,
})
