#!/usr/bin/env bash
# Fails when a tracked or new (not ignored) text file contains an em-dash
# (U+2014) or an emoji. Prints file:line for every hit. Fuzz corpora are
# skipped because they hold generated bytes.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

files=()
while IFS= read -r -d '' file; do
	[[ -f "$file" ]] || continue
	case "$file" in
	*/testdata/fuzz/*) continue ;;
	esac
	# grep -I treats binary files as non-matching; empty files are skipped too.
	grep -Iq . "$file" || continue
	files+=("$file")
done < <(git ls-files -z --cached --others --exclude-standard)

status=0
# One perl run for the whole tree: starting an interpreter per file costs far
# more than the scan itself. Closing ARGV at each end of file restarts the line
# counter on the next one.
#
# Extended_Pictographic is the Unicode property behind every emoji, including
# the ones outside the emoji blocks (U+2705, U+26A0, U+2714, U+2B50); it leaves
# out the box drawing, arrow, geometric and Nerd Font characters the status
# line and the TUI draw with. The copyright, registered and trademark signs
# carry the property but are typographic marks, so they stay allowed. The emoji
# blocks cover what the property leaves out: regional indicators (flags) and the
# variation selector.
if ((${#files[@]} > 0)) && ! perl -CSD -ne '
	if (/\x{2014}|[\x{1F000}-\x{1FAFF}]|\x{FE0F}|(?![\x{00A9}\x{00AE}\x{2122}])\p{Extended_Pictographic}/) { print "$ARGV:$.: $_"; $hit = 1 }
	close ARGV if eof;
	END { exit($hit ? 1 : 0) }
' "${files[@]}" 2>/dev/null; then
	status=1
fi

if ((status != 0)); then
	echo "check-text: remove em-dashes (U+2014) and emojis listed above" >&2
fi
exit "$status"
